// src/lib/locations.ts

export type LocationOption = {
  value: string;
  label: string;
};

export type CityData = {
  city: LocationOption;
  neighborhoods: LocationOption[];
};

export const saudiLocations: CityData[] = [
  {
    city: { value: 'riyadh', label: 'الرياض (Riyadh)' },
    neighborhoods: [
      { value: 'ad_dar_al_baida', label: 'Ad Dar Al Baida' },
      { value: 'ad_difa', label: 'Ad Difa' },
      { value: 'ad_dirah', label: 'Ad Dirah' },
      { value: 'ad_dubiyah', label: 'Ad Dubiyah' },
      { value: 'ad_duraihimiyah', label: 'Ad Duraihimiyah' },
      { value: 'adh_dhubbat', label: 'Adh Dhubbat' },
      { value: 'al_amal', label: 'Al Amal' },
      { value: 'al_andalus', label: 'Al Andalus' },
      { value: 'al_aqiq', label: 'Al Aqiq' },
      { value: 'al_arid', label: 'Al Arid' },
      { value: 'al_aziziyah', label: 'Al Aziziyah' },
      { value: 'al_badiah', label: 'Al Badiah' },
      { value: 'al_bariah', label: 'Al Bariah' },
      { value: 'al_batha', label: 'Al Batha' },
      { value: 'al_dho', label: 'Al Dho' },
      { value: 'al_faiha', label: 'Al Faiha' },
      { value: 'al_faisaliyah', label: 'Al Faisaliyah' },
      { value: 'al_fakhriyah', label: 'Al Fakhriyah' },
      { value: 'al_falah', label: 'Al Falah' },
      { value: 'al_faruq', label: 'Al Faruq' },
      { value: 'al_futah', label: 'Al Futah' },
      { value: 'al_ghadir', label: 'Al Ghadir' },
      { value: 'al_ghnamiah', label: 'Al Ghnamiah' },
      { value: 'ghirnatah', label: 'Ghirnatah' },
      { value: 'ghubairah', label: 'Ghubairah' },
      { value: 'al_hada', label: 'Al Hada' },
      { value: 'al_haer', label: 'Al Haer' },
      { value: 'al_hamra', label: 'Al Hamra' },
      { value: 'al_hazm', label: 'Al Hazm' },
      { value: 'hittin', label: 'Hittin' },
      { value: 'hyt', label: 'Hyt' },
      { value: 'ilaishah', label: 'Ilaishah' },
      { value: 'al_imam_muhammed', label: 'Al Imam Muhammed Ibn Saud Islamic University' },
      { value: 'al_iskan', label: 'Al Iskan' },
      { value: 'al_izdihar', label: 'Al Izdihar' },
      { value: 'irqah', label: 'Irqah' },
      { value: 'ishbiliyah', label: 'Ishbiliyah' },
      { value: 'al_janadriyah', label: 'Al Janadriyah' },
      { value: 'al_jaradiyah', label: 'Al Jaradiyah' },
      { value: 'al_jazirah', label: 'Al Jazirah' },
      { value: 'jabrah', label: 'Jabrah' },
      { value: 'jarir', label: 'Jarir' },
      { value: 'al_khalidiyah', label: 'Al Khalidiyah' },
      { value: 'al_khalij', label: 'Al Khalij' },
      { value: 'al_khuzama', label: 'Al Khuzama' },
      { value: 'khashm_al_an', label: 'Khashm Al An' },
      { value: 'king_abdul_aziz', label: 'King Abdul Aziz' },
      { value: 'king_abdullah', label: 'King Abdullah' },
      { value: 'king_fahd', label: 'King Fahd' },
      { value: 'king_faisal', label: 'King Faisal' },
      { value: 'king_khalid_airport', label: 'King Khalid Airport' },
      { value: 'king_saud_university', label: 'King Saud University' },
      { value: 'laban', label: 'Laban' },
      { value: 'al_madhar', label: 'Al Madhar' },
      { value: 'al_madhar_ash_shamali', label: 'Al Madhar Ash Shamali' },
      { value: 'al_mahdiyah', label: 'Al Mahdiyah' },
      { value: 'al_maizilah', label: 'Al Maizilah' },
      { value: 'al_malaz', label: 'Al Malaz' },
      { value: 'al_malqa', label: 'Al Malqa' },
      { value: 'al_manakh', label: 'Al Manakh' },
      { value: 'al_manar', label: 'Al Manar' },
      { value: 'al_mansurah', label: 'Al Mansurah' },
      { value: 'al_marqab', label: 'Al Marqab' },
      { value: 'al_marwah', label: 'Al Marwah' },
      { value: 'al_masani', label: 'Al Masani' },
      { value: 'al_masif', label: 'Al Masif' },
      { value: 'al_mikal', label: 'Al Mikal' },
      { value: 'al_misfat', label: 'Al Misfat' },
      { value: 'al_mishal', label: 'Al Mishal' },
      { value: 'al_mughrizat', label: 'Al Mughrizat' },
      { value: 'al_muhammadiyah', label: 'Al Muhammadiyah' },
      { value: 'al_munsiyah', label: 'Al Munsiyah' },
      { value: 'al_murabba', label: 'Al Murabba' },
      { value: 'al_mursalat', label: 'Al Mursalat' },
      { value: 'al_muruj', label: 'Al Muruj' },
      { value: 'al_mutamarat', label: 'Al Mutamarat' },
      { value: 'al_muzahimiyah', label: 'Al Muzahimiyah' },
      { value: 'manfuhah', label: 'Manfuhah' },
      { value: 'manfuhah_al_jadidah', label: 'Manfuhah Al Jadidah' },
      { value: 'mansuriyah', label: 'Mansuriyah' },
      { value: 'an_nada', label: 'An Nada' },
      { value: 'an_nafl', label: 'An Nafl' },
      { value: 'an_nahdah', label: 'An Nahdah' },
      { value: 'an_nakhil', label: 'An Nakhil' },
      { value: 'an_namudhajiyah', label: 'An Namudhajiyah' },
      { value: 'an_narjis', label: 'An Narjis' },
      { value: 'an_nasim_al_gharbi', label: 'An Nasim Al Gharbi' },
      { value: 'an_nasim_ash_sharqi', label: 'An Nasim Ash Sharqi' },
      { value: 'an_nasriyah', label: 'An Nasriyah' },
      { value: 'an_nazim', label: 'An Nazim' },
      { value: 'an_nur', label: 'An Nur' },
      { value: 'an_nuzhah', label: 'An Nuzhah' },
      { value: 'namar', label: 'Namar' },
      { value: 'al_qadisiyah', label: 'Al Qadisiyah' },
      { value: 'al_qirawan', label: 'Al Qirawan' },
      { value: 'al_quds', label: 'Al Quds' },
      { value: 'al_qura', label: 'Al Qura' },
      { value: 'qurtubah', label: 'Qurtubah' },
      { value: 'ar_rabi', label: 'Ar Rabi' },
      { value: 'ar_rabwah', label: 'Ar Rabwah' },
      { value: 'ar_rafiah', label: 'Ar Rafiah' },
      { value: 'ar_rahmaniyah', label: 'Ar Rahmaniyah' },
      { value: 'ar_raid', label: 'Ar Raid' },
      { value: 'ar_rawabi', label: 'Ar Rawabi' },
      { value: 'ar_rufa', label: 'Ar Rufa\'' },
      { value: 'salah_ad_din', label: 'Salah Ad Din' },
      { value: 'al_ulaya', label: 'Al Ulaya' },
      { value: 'al_umjiah', label: 'Al Umjiah' },
      { value: 'al_uraija', label: 'Al Uraija' },
      { value: 'al_uraija_al_gharbiyah', label: 'Al Uraija Al Gharbiyah' },
      { value: 'al_uraija_al_wusta', label: 'Al Uraija Al Wusta' },
      { value: 'al_wadi', label: 'Al Wadi' },
      { value: 'al_wahah', label: 'Al Wahah' },
      { value: 'wadi_laban', label: 'Wadi Laban' },
      { value: 'al_wazarat', label: 'Al Wazarat' },
      { value: 'al_wisham', label: 'Al Wisham' },
      { value: 'al_wurud', label: 'Al Wurud' },
      { value: 'al_wusayta', label: 'Al Wusayta' },
      { value: 'al_yamamah', label: 'Al Yamamah' },
      { value: 'al_yarmuk', label: 'Al Yarmuk' },
      { value: 'al_yasmin', label: 'Al Yasmin' },
      { value: 'afif', label: 'Afif' },
      { value: 'badr', label: 'Badr' },
      { value: 'banban', label: 'Banban' },
      { value: 'dahiat_namar', label: 'Dahiat Namar' },
      { value: 'dhahrat_al_badiah', label: 'Dhahrat Al Badiah' },
      { value: 'dhahrat_laban', label: 'Dhahrat Laban' },
      { value: 'dhahrat_namar', label: 'Dhahrat Namar' },
      { value: 'dirab', label: 'Dirab' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'jeddah', label: 'جدة (Jeddah)' },
    neighborhoods: [
      { value: 'al_safa', label: 'الصفا (Al Safa)' },
      { value: 'al_hamra', label: 'الحمراء (Al Hamra)' },
      { value: 'al_balad', label: 'البلد (Al Balad)' },
      { value: 'al_rawdah', label: 'الروضة (Al Rawdah)' },
      { value: 'al_naeem', label: 'النعيم (Al Naeem)' },
      { value: 'al_mohammadiyyah', label: 'المحمدية (Al Mohammadiyyah)' },
      { value: 'al_basateen', label: 'البساتين (Al Basateen)' },
      { value: 'al_khalidiya', label: 'الخالدية (Al Khalidiya)' },
      { value: 'al_salamah', label: 'السلامة (Al Salamah)' },
      { value: 'al_zahra', label: 'الزهراء (Al Zahra)' },
      { value: 'al_bawadi', label: 'البوادي (Al Bawadi)' },
      { value: 'al_nuzhah', label: 'النزهة (Al Nuzhah)' },
      { value: 'al_faisaliyah', label: 'الفيصلية (Al Faisaliyah)' },
      { value: 'al_marwah', label: 'المروة (Al Marwah)' },
      { value: 'obhur_al_janoubiyah', label: 'أبحر الجنوبية (Obhur Al Janoubiyah)' },
      { value: 'obhur_al_shamaliyah', label: 'أبحر الشمالية (Obhur Al Shamaliyah)' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'dammam', label: 'الدمام (Dammam)' },
    neighborhoods: [
      { value: 'al_faisaliyah', label: 'الفيصلية (Al Faisaliyah)' },
      { value: 'al_jalawiyah', label: 'الجلوية (Al Jalawiyah)' },
      { value: 'al_shati', label: 'الشاطئ (Al Shati)' },
      { value: 'uhud', label: 'أحد (Uhud)' },
      { value: 'al_fursan', label: 'الفرسان (Al Fursan)' },
      { value: 'ad_danah', label: 'الدانہ (Ad Danah)' },
      { value: 'al_badiyah', label: 'البادية (Al Badiyah)' },
      { value: 'al_dawasir', label: 'الدواسر (Al Dawasir)' },
      { value: 'al_muraikabat', label: 'المريكبات (Al Muraikabat)' },
      { value: 'al_muntazah', label: 'المنتزه (Al Muntazah)' },
      { value: 'al_rakah_dammam', label: 'الراكة (Al Rakah)' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'mecca', label: 'مكة المكرمة (Mecca)' },
    neighborhoods: [
      { value: 'al_aziziyah', label: 'العزيزية (Al Aziziyah)' },
      { value: 'al_awali', label: 'العوالي (Al Awali)' },
      { value: 'al_shawqiyyah', label: 'الشوقية (Al Shawqiyyah)' },
      { value: 'al_kakiyyah', label: 'الكعكية (Al Kakiyyah)' },
      { value: 'ajyad', label: 'أجياد (Ajyad)' },
      { value: 'al_misfalah', label: 'المسفلة (Al Misfalah)' },
      { value: 'al_maabda', label: 'المعابدة (Al Maabda)' },
      { value: 'al_rasaifah', label: 'الرصيفة (Al Rasaifah)' },
      { value: 'al_zahra_mecca', label: 'الزهراء (Al Zahra)' },
      { value: 'jabal_omar', label: 'جبل عمر (Jabal Omar)' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'medina', label: 'المدينة المنورة (Medina)' },
    neighborhoods: [
      { value: 'al_harra', label: 'الحرة (Al Harra)' },
      { value: 'al_qiblatayn', label: 'القبلتين (Al Qiblatayn)' },
      { value: 'quba', label: 'قباء (Quba)' },
      { value: 'al_awali_medina', label: 'العوالي (Al Awali)' },
      { value: 'al_iskan', label: 'الاسكان (Al Iskan)' },
      { value: 'al_azhariyyah', label: 'الأزهرية (Al Azhariyyah)' },
      { value: 'al_khalidiyyah_medina', label: 'الخالدية (Al Khalidiyyah)' },
      { value: 'sayyid_al_shuhada', label: 'سيد الشهداء (Sayyid Al Shuhada)' },
      { value: 'quraidha', label: 'قريضة (Quraidha)' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'khobar', label: 'الخبر (Khobar)' },
    neighborhoods: [
      { value: 'al_aqrabiyah', label: 'العقربية (Al Aqrabiyah)' },
      { value: 'al_hizam', label: 'الحزام الذهبي (Al Hizam)' },
      { value: 'al_thuqbah', label: 'الثقبة (Al Thuqbah)' },
      { value: 'al_rakah_janubiyah', label: 'الراكة الجنوبية (Al Rakah Al Janubiyah)' },
      { value: 'al_khuzama', label: 'الخزامى (Al Khuzama)' },
      { value: 'al_jisr', label: 'الجسر (Al Jisr)' },
      { value: 'al_yarmouk_khobar', label: 'اليرموك (Al Yarmouk)' },
      { value: 'al_bandariyah', label: 'البندرية (Al Bandariyah)' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'taif', label: 'الطائف (Taif)' },
    neighborhoods: [
      { value: 'al_shafa', label: 'الشفا (Al Shafa)' },
      { value: 'al_hada', label: 'الهدا (Al Hada)' },
      { value: 'al_hawiyah', label: 'الحوية (Al Hawiyah)' },
      { value: 'al_khalidiya_taif', label: 'الخالدية (Al Khalidiya)' },
      { value: 'al_faisaliyah_taif', label: 'الفيصلية (Al Faisaliyah)' },
      { value: 'qarooy', label: 'قروى (Qarooy)' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'tabuk', label: 'تبوك (Tabuk)' },
    neighborhoods: [
      { value: 'al_muruj', label: 'المروج (Al Muruj)' },
      { value: 'al_olaya_tabuk', label: 'العليا (Al Olaya)' },
      { value: 'al_mahrajan', label: 'المهرجان (Al Mahrajan)' },
      { value: 'al_rawdah_tabuk', label: 'الروضة (Al Rawdah)' },
      { value: 'al_faisaliyah_tabuk', label: 'الفيصلية (Al Faisaliyah)' },
      { value: 'al_sulaimaniyah_tabuk', label: 'السليمانية (Al Sulaimaniyah)' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'buraidah', label: 'بريدة (Buraidah)' },
    neighborhoods: [
      { value: 'al_iskan_buraidah', label: 'الاسكان (Al Iskan)' },
      { value: 'al_montazah', label: 'المنتزه (Al Montazah)' },
      { value: 'al_rayyan', label: 'الريان (Al Rayyan)' },
      { value: 'al_rabie_buraidah', label: 'الربيع (Al Rabie)' },
      { value: 'al_safra', label: 'الصفراء (Al Safra)' },
      { value: 'al_basr', label: 'البصر (Al Basr)' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'abha', label: 'أبها (Abha)' },
    neighborhoods: [
      { value: 'al_manhal', label: 'المنهل (Al Manhal)' },
      { value: 'al_khaldiyah_abha', label: 'الخالدية (Al Khaldiyah)' },
      { value: 'al_nuzhah_abha', label: 'النزهة (Al Nuzhah)' },
      { value: 'al_qabil', label: 'القابل (Al Qabil)' },
      { value: 'al_sir', label: 'السروات (Al Sir)' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'jubail', label: 'الجبيل (Jubail)' },
    neighborhoods: [
      { value: 'al_huwaylat', label: 'الحويلات (Al Huwaylat)' },
      { value: 'al_fandouq', label: 'الفندق (Al Fandouq)' },
      { value: 'al_deffi', label: 'الدفي (Al Deffi)' },
      { value: 'al_fanateer', label: 'الفناتير (Al Fanateer)' },
      { value: 'jalmudah', label: 'جلمودة (Jalmudah)' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'hail', label: 'حائل (Hail)' },
    neighborhoods: [
      { value: 'al_jamiyin', label: 'الجامعيين (Al Jamiyin)' },
      { value: 'al_muntazah_hail', label: 'المنتزه (Al Muntazah)' },
      { value: 'al_shifa', label: 'الشفا (Al Shifa)' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'najran', label: 'نجران (Najran)' },
    neighborhoods: [
      { value: 'abalaa', label: 'أبا السعود (Abalaa)' },
      { value: 'al_faisaliah_najran', label: 'الفيصلية (Al Faisaliah)' },
      { value: 'al_shurfah', label: 'الشرفة (Al Shurfah)' },
      { value: 'other', label: 'أخرى (Other)' },
    ],
  },
  {
    city: { value: 'other_city', label: 'مدينة أخرى (Other City)' },
    neighborhoods: [
      { value: 'other', label: 'أخرى (Other)' },
    ]
  }
];

export function getNeighborhoodsForCity(cityValue: string): LocationOption[] {
  const city = saudiLocations.find(c => c.city.value === cityValue);
  return city ? city.neighborhoods : [];
}

export function getCityLabel(value: string): string {
    const city = saudiLocations.find(c => c.city.value === value);
    return city ? city.city.label : value;
}

export function getNeighborhoodLabel(cityValue: string, neighborhoodValue: string): string {
    const city = saudiLocations.find(c => c.city.value === cityValue);
    if (!city) return neighborhoodValue;
    const hood = city.neighborhoods.find(n => n.value === neighborhoodValue);
    return hood ? hood.label : neighborhoodValue;
}
